/* eslint-disable */
// Auto-generated by generate-protos script on Tue Aug 20 2024 14:35:03 GMT-0400 (Eastern Daylight Time)

import Protobuf from 'protobufjs';
import type {Type as ProtoType} from 'protobufjs';
const Schema:{[name: string]: ProtoType} = {};

const encrypted_app_ticket:any = {"options":{"optimize_for":"SPEED","cc_generic_services":false},"nested":{"EncryptedAppTicket":{"fields":{"ticket_version_no":{"type":"uint32","id":1},"crc_encryptedticket":{"type":"uint32","id":2},"cb_encrypteduserdata":{"type":"uint32","id":3},"cb_encrypted_appownershipticket":{"type":"uint32","id":4},"encrypted_ticket":{"type":"bytes","id":5}}}}};

Object.assign(Schema, Protobuf.Root.fromJSON(encrypted_app_ticket));

export default Schema;
